server:
  port: 8081
spring:
  application:
    name: item-services
  datasource:
    name: zp
    url: jdbc:mysql://localhost:3306/zp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#  rabbitmq:
#    host: 192.168.199.1
#    virtual-host: /zp
#    username: zp
#    password: zp
#    template:
#      exchange: ZP.ITEM.EXCHANGE

logging:
  level:
    com.itemservice.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.iteminterfaces.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法

pagehelper:
  helperDialect: mysql
  reasonable: true  #开启优化，如果开启优化，在分页页码结果没有数据的时候,会显示有数据的页码数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  pageSizeZero: false #pageSize=0 返回所有
  params: count=countSql