server:
  port: 10086
spring:
  application:
    name: register
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  server:
    enable-self-preservation: false #关闭自我保护模式
    eviction-interval-timer-in-ms: 10000 #10秒清理一次无效连接