server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.199.1
    virtual-host: /zp
    username: zp
    password: zp
leyou:
  sms:
    accessKeyId: JWffwFJIwada
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ
    signName: 曾沛商城
    verifyCodeTemplate: SMS_13539362046