server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    name: zp
    url: jdbc:mysql://localhost:3306/zp?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  redis:
    host: 192.168.154.129
  rabbitmq:
    host: 192.168.199.1
    virtual-host: /zp
    username: zp
    password: zp
logging:
  level:
    com.itemservice.mapper: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.userinterfaces.pojo
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法

