#购物车配置文件
server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 127.0.0.1
leyou:
  jwt:
    pubKeyPath: D:\\SSM\\rsa.pub  #公钥地址
    cookieName: LY_TOKEN
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15